name: Checkout new source (legacy)

on:
  workflow_dispatch:
  schedule:
    - cron: "23 0,6,12,18 * * *" # China Time 0820 1420 2020 2620
    
concurrency:
  group: update-code-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetchXPI_standard:
    uses: ./.github/workflows/fetchZip01.yml
    with:
      filename_suffix: '-legacy'
      monaco_version: '0.30.1'
